from tkinter import *

class Box:

    def __init__(self, canv, x, y, height, width, depth, color):
        self.canv = canv
        self.x = x
        self.y = y
        self.height = height
        self.width = width
        self.color = color
        self.depth = depth

    def start_box(self):
        self.draw_box(self.x, self.y, 400, 400, self.depth)

    def draw_box(self, x1,y1,x2,y2,depth):
        #base case
        if depth==0:
            self.draw_rectangle(x1, y1, x2, y2)
            return
        #recursive case finds the coordinates of the intermediate points (one third and two thirds of the line)
        else:
            l_x1=x1 + (x2-x1)/3
            l_x2=x1 + 2*(x2-x1)/3
            l_y1=y1 + (y2-y1)/3
            l_y2=y1 + 2*(y2-y1)/3

            self.draw_rectangle(x1,y1,l_x1,l_y1)
            self.draw_rectangle(l_x2,y1,x2,l_y1)
            self.draw_rectangle(x1,l_y2,l_x1,y2)
            self.draw_rectangle(l_x2,l_y2,x2,y2)

            self.draw_box(l_x1,y1,l_x2,l_y1,depth-1)
            self.draw_box(x1,l_y1,l_x1,l_y2,depth-1)
            self.draw_box(l_x1,l_y1,l_x2,l_y2,depth-1)
            self.draw_box(l_x2,l_y1,x2,l_y2,depth-1)
            self.draw_box(l_x1,l_y2,l_x2,y2,depth-1)

    def draw_rectangle(self, x0, y0, x1, y1):
        self.canv.create_rectangle(x0, y0, x1, y1, fill=self.color)
    
#Code generated by Chat-GPT pretty cool

    # def draw_fractal(self, x, y, width, height):
    #     if width < 5 or height < 5:
    #         return
        
    #     # Calculate the coordinates of the four smaller boxes
    #     x1 = x + width / 3
    #     y1 = y + height / 3
    #     x2 = x + (width / 3) * 2
    #     y2 = y + (height / 3) * 2
        
    #     # Draw the four smaller boxes
    #     self.draw_rectangle(x1, y, x2, y1)
    #     self.draw_rectangle(x1, y2, x2, y)
    #     self.draw_rectangle(x, y1, x1, y2)
    #     self.draw_rectangle(x2, y1, x, y2)
        
    #     # Recursively draw the smaller boxes
    #     self.draw_fractal(x1, y1, width / 3, height / 3)
    #     self.draw_fractal(x1, y2, width / 3, height / 3)
    #     self.draw_fractal(x2, y1, width / 3, height / 3)
    #     self.draw_fractal(x2, y2, width / 3, height / 3)

            

    

    

    

    